apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sensor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sensor
    spec:
      containers:
      - name: sensor
        image: brusmx/iot-hub-experiment
        env:
        - name: CONNECTION_STRING
          value: ""
        - name: DEVICE_ID
          value: ""
        imagePullPolicy: Always
